### ISSUE TITLE
Making a website to serve analysis

### ISSUE THREAD

**Issue by davidgasquez** [jwinternheimer/analysis#2]
Hey @jwinternheimer! Wanted to share an idea with you. 😄 Since the files are Markdown it could be really easy to serve them using a static website engine like Hugo or Jekyll. 

Would love to try something during our hackdays! 😃 

### Resources
- https://github.com/rstudio/blogdown
- https://proquestionasker.github.io/blog/Making_Site/

**Comment by jwinternheimer** [comment]
Heck yeah @davidgasquez, I would be super excited about this!! I was researching with blogdown recently and it looks very intuitive and straightforward!

Would absolutely love to hack on something that makes analysis easier to serve and discover for the whole team (and internet). 😬 

![bitmoji](https://render.bitstrips.com/v2/cpanel/8398479-132098438_13-s1-v1.png?transparent=1&palette=1&width=246)

**Comment by davidgasquez** [comment]
Nice work @jwinternheimer! Excited to see the site evolving 🏆
